// Independent literals transcribed from each adapter's real-client
// COMPATIBILITY.md and fixtures/README.md observations as they existed before
// Task 6. This module deliberately imports neither manifests nor provenance.
const row = (capability, fixture, event, tool, outcome, idleBehavior, busyBehavior,
  authorityLevel, limitations) => ({ capability, fixture, event, tool, outcome,
  idleBehavior, busyBehavior, authorityLevel, limitations });

const nextTurn = (fixture, event, limitation) => row("delivery.nextTurn", fixture,
  event, null, "model-context-observed", "offers complete peer messages at the next prompt",
  "does not interrupt an in-progress turn", "context", [limitation]);

const withFacts = (client, version, entries) => entries.map(entry => ({ client, version,
  platform: "darwin-arm64", observedAt: "2026-08-16", ...entry }));

export const PASS_EXPECTATIONS = Object.freeze({
  "adapter-claude-code": withFacts("claude-code", "2.1.233", [
    row("lifecycle.sessionStart", "fixtures/SessionStart.json", "SessionStart", null,
      "event-observed", "fires when a session starts", "fires before the first model turn",
      "advisory", ["capture used a one-session --plugin-dir"]),
    row("lifecycle.sessionEnd", "fixtures/SessionEnd.json", "SessionEnd", null,
      "event-observed", "fires when a session exits", "does not run until the session exits",
      "advisory", ["cannot write a handoff after the model has stopped"]),
    row("context.beforeTurnInjection", "fixtures/UserPromptSubmit.json", "UserPromptSubmit",
      null, "model-context-observed", "waits for the next user prompt",
      "does not interrupt an in-progress turn", "context",
      ["requires the hookSpecificOutput additionalContext envelope"]),
    row("guards.beforeWrite", "fixtures/PreToolUse-Edit.json", "PreToolUse", "Edit",
      "tool-denied-before-mutation", "no write exists to guard",
      "denies a file edit before disk mutation", "blocking",
      ["runtime writes are outside the hook boundary"]),
    row("guards.beforeShell", "fixtures/PreToolUse.json", "PreToolUse", "Bash",
      "tool-denied-before-execution", "no shell call exists to guard",
      "denies a Bash call before execution", "blocking",
      ["only tool calls reaching PreToolUse are guarded"]),
    nextTurn("fixtures/UserPromptSubmit.json", "UserPromptSubmit",
      "delivery requires the next normal user turn"),
  ]),
  "adapter-codex": withFacts("codex-cli", "0.147.0", [
    row("lifecycle.sessionStart", "fixtures/SessionStart.json", "SessionStart", null,
      "event-observed", "fires when a client session starts",
      "fires before the first model turn", "advisory",
      ["plugin hooks must be explicitly trusted by the user"]),
    row("lifecycle.sessionEnd", "fixtures/SessionEnd.json", "SessionEnd", null,
      "event-observed", "fires when a client session exits",
      "does not run until the session exits", "advisory",
      ["plugin hooks must be explicitly trusted by the user"]),
    row("context.beforeTurnInjection", "fixtures/UserPromptSubmit.json", "UserPromptSubmit",
      null, "model-context-observed", "waits for the next user prompt",
      "does not interrupt an in-progress turn", "context",
      ["stdout arrives as an unwrapped developer-role message"]),
    row("guards.beforeWrite", "fixtures/PreToolUse.json", "PreToolUse", "apply_patch",
      "tool-denied-before-mutation", "no write exists to guard",
      "blocks an apply_patch call before disk mutation", "blocking",
      ["runtime and unrecognised shell writes can bypass the guard"]),
    nextTurn("fixtures/UserPromptSubmit.json", "UserPromptSubmit",
      "delivery requires the next normal user turn"),
  ]),
  "adapter-gemini-cli": withFacts("gemini-cli", "0.37.0", [
    row("lifecycle.sessionStart", "fixtures/SessionStart.json", "SessionStart", null,
      "event-observed", "fires when a session starts", "fires before the first model turn",
      "advisory", ["capture used temporary project settings"]),
    row("lifecycle.sessionEnd", "fixtures/SessionEnd.json", "SessionEnd", null,
      "event-observed", "fires when a session exits", "does not run until the session exits",
      "advisory", ["handoff must be written before session end"]),
    row("context.beforeTurnInjection", "fixtures/BeforeAgent.json", "BeforeAgent", null,
      "model-context-observed", "waits for the next user prompt",
      "does not interrupt an in-progress turn", "context",
      ["requires the hookSpecificOutput additionalContext envelope"]),
    row("guards.beforeWrite", "fixtures/BeforeTool.json", "BeforeTool", "write_file",
      "tool-denied-before-mutation", "no write exists to guard",
      "blocks write_file before mutation", "blocking",
      ["write tools are unavailable in plan mode"]),
    row("guards.beforeShell", "fixtures/BeforeTool-shell.json", "BeforeTool",
      "run_shell_command", "tool-denied-before-execution", "no shell call exists to guard",
      "blocks run_shell_command before execution", "blocking",
      ["shell tools depend on approval mode"]),
    nextTurn("fixtures/BeforeAgent.json", "BeforeAgent",
      "delivery requires the next normal user turn"),
  ]),
  "adapter-grok": [],
  "adapter-kimi": withFacts("kimi", "0.36.1", [
    row("lifecycle.sessionStart", "fixtures/SessionStart.json", "SessionStart", null,
      "event-observed", "fires when a session starts", "fires before the first model turn",
      "advisory", ["prompt-mode session end is not emitted"]),
    row("lifecycle.heartbeat", "fixtures/SessionHeartbeat.json", "SessionHeartbeat", null,
      "fixed-cadence-observed", "fires every 60 seconds while idle",
      "continues on the same fixed cadence", "advisory",
      ["a process that exits before one minute emits no heartbeat"]),
    row("context.beforeTurnInjection", "fixtures/UserPromptSubmit.json", "UserPromptSubmit",
      null, "model-context-observed", "waits for the next user prompt",
      "does not interrupt an in-progress turn", "context",
      ["the client wraps raw stdout as hook_result"]),
    row("guards.beforeWrite", "fixtures/PreToolUse-Write.json", "PreToolUse", "Write",
      "tool-denied-before-mutation", "no write exists to guard",
      "denies Write before mutation", "blocking",
      ["runtime writes are outside the hook boundary"]),
    row("guards.beforeShell", "fixtures/PreToolUse-Bash.json", "PreToolUse", "Bash",
      "tool-denied-before-execution", "no shell call exists to guard",
      "denies Bash before execution", "blocking",
      ["only tool calls reaching PreToolUse are guarded"]),
    nextTurn("fixtures/UserPromptSubmit.json", "UserPromptSubmit",
      "delivery requires the next normal user turn"),
  ]),
});
