import { access, chmod, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { AccError, EXIT } from "@agents-can-communicate/protocol";

/**
 * Where the hook runtime lives, resolved from this package rather than looked
 * up on PATH. A hook's environment does not reliably carry the user's PATH, and
 * a command that cannot be found fails silently on every event.
 */
export const defaultRunner = () =>
  fileURLToPath(new URL("../../../bin/acc-hook.mjs", import.meta.url));

export const runnerExists = async runner => {
  try {
    await access(runner);
    return true;
  } catch {
    return false;
  }
};

export async function assertRunner(runner) {
  if (!await runnerExists(runner)) {
    throw new AccError(EXIT.DATA,
      "refusing to install: the hook runner does not exist", { runner });
  }
  return runner;
}

// Shell metacharacters in a path are the caller's problem to survive, not the
// shell's to interpret.
const quote = value => `"${String(value).replace(/(["\\$`])/g, "\\$1")}"`;

/**
 * Write the small shim a client's hook command points at.
 *
 * Clients disagree about how a hook command may be written - some expand a
 * plugin-root variable, some demand an absolute path, one has no variable at
 * all - but every one of them can run a shell script. The shim absorbs that
 * difference and pins the interpreter and the runner to absolute paths at
 * install time.
 */
export async function writeHookShim({ dir, adapterId, runner = defaultRunner(),
  node = process.execPath, name = "acc-hook.sh" }) {
  await assertRunner(runner);
  const target = path.join(dir, name);
  await mkdir(dir, { recursive: true });
  await writeFile(target, [
    "#!/bin/sh",
    "# Generated by ACC at install time. The paths are pinned deliberately:",
    "# a hook runs with an environment that may carry neither PATH nor a shell",
    "# profile, and a command that cannot be found fails silently on every event.",
    `exec ${quote(node)} ${quote(runner)} ${adapterId} "$@"`,
    "",
  ].join("\n"));
  await chmod(target, 0o755);
  return target;
}

/**
 * Remove a directory this adapter installed, unless it has been kept back.
 *
 * The installer decides what may be deleted by comparing what is on disk
 * against what ACC recorded writing. An adapter that removed its layout
 * unconditionally would undo that decision - and the case it undoes is exactly
 * the one that matters: someone put their own work inside a directory ACC
 * created, and a recognised path is not a reason to delete it.
 */
export async function removeInstalledTree(target, keep = []) {
  if (keep.includes(target)) return false;
  await rm(target, { recursive: true, force: true });
  return true;
}
