import { access, chmod, lstat, mkdir, readFile, readdir, rm, writeFile }
  from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { AccError, EXIT } from "@agents-can-communicate/protocol";

/**
 * Where the hook runtime lives, resolved from this package rather than looked
 * up on PATH. A hook's environment does not reliably carry the user's PATH, and
 * a command that cannot be found fails silently on every event.
 */
/**
 * The hook runner, found rather than counted to.
 *
 * `../../../bin/acc-hook.mjs` is the answer in a development checkout and only
 * there. Published, this module sits at
 * `<package>/node_modules/@agents-can-communicate/adapter-sdk/src/`, which is one
 * level deeper, so the path resolved to `node_modules/bin/acc-hook.mjs` and
 * every install refused: `the hook runner does not exist`, for every client on
 * the machine, from a clean `npm install` of the package.
 *
 * Nothing caught it. `acc install` exited 0 with the failures counted in a line
 * that began with a success, and the release check threw that output away - so
 * the gate reported PASS on a package whose main command could not run.
 *
 * Walking up for it holds in both layouts and in whatever a future one is: the
 * nearest `bin/acc-hook.mjs` above this file is the one that belongs to this
 * copy of the package.
 */
/**
 * A binary of this package's own, found by walking up rather than counted to.
 *
 * `../../../bin/<name>` is the answer in a development checkout and only there.
 * Published, this module sits at
 * `<package>/node_modules/@agents-can-communicate/adapter-sdk/src/`, one level
 * deeper - so the count landed on `node_modules/bin/<name>`, which does not
 * exist. That was found once for the hook runner and fixed for the runner
 * alone. The CLI kept the count, and every skill installed for every agent
 * named a command that could not run: an agent that followed it got
 * `MODULE_NOT_FOUND`. Found by asking a real client to edit a claimed file and
 * reading what it reported.
 */
const ownBinary = name => {
  let directory = fileURLToPath(new URL(".", import.meta.url));
  for (;;) {
    const candidate = path.join(directory, "bin", name);
    if (existsSync(candidate)) return candidate;
    const parent = path.dirname(directory);
    // Reached the root without finding one. The development answer is returned
    // so the refusal that follows names a path a reader can recognise.
    if (parent === directory) {
      return fileURLToPath(new URL(`../../../bin/${name}`, import.meta.url));
    }
    directory = parent;
  }
};

export const defaultRunner = () => ownBinary("acc-hook.mjs");
export const defaultBootstrap = () => ownBinary("acc-bootstrap.mjs");
export const defaultChannel = () => ownBinary("acc-claude-channel.mjs");

export const runnerExists = async runner => {
  try {
    await access(runner);
    return true;
  } catch {
    return false;
  }
};

export async function assertRunner(runner) {
  if (!await runnerExists(runner)) {
    throw new AccError(EXIT.DATA,
      "refusing to install: the hook runner does not exist", { runner });
  }
  return runner;
}

// What the shipped skill carries where the runnable command belongs.
const PLACEHOLDER = "{{ACC}}";

// Shell metacharacters in a path are the caller's problem to survive, not the
// shell's to interpret.
const quote = value => `"${String(value).replace(/(["\\$`])/g, "\\$1")}"`;

/**
 * Write the small shim a client's hook command points at.
 *
 * Clients disagree about how a hook command may be written - some expand a
 * plugin-root variable, some demand an absolute path, one has no variable at
 * all - but every one of them can run a shell script. The shim absorbs that
 * difference and pins the interpreter and the runner to absolute paths at
 * install time.
 */
export async function writeHookShim({ dir, adapterId, runner = defaultRunner(),
  node = process.execPath, name = "acc-hook.sh", dataHome }) {
  await assertRunner(runner);
  const target = path.join(dir, name);
  await mkdir(dir, { recursive: true });
  await writeFile(target, [
    "#!/bin/sh",
    "# Generated by ACC at install time. The paths are pinned deliberately:",
    "# a hook runs with an environment that may carry neither PATH nor a shell",
    "# profile, and a command that cannot be found fails silently on every event.",
    "#",
    "# Pinned first, and then asked for, because the pinned pair moves. A node",
    "# version manager changes both the interpreter and the directory global",
    "# packages live in, and a shim naming the old ones failed on every event",
    "# with nothing to read but exit 126 - no presence, no claims, no messages,",
    "# and nothing anywhere saying why.",
    `ACC_NODE=${quote(node)}`,
    `ACC_RUNNER=${quote(runner)}`,
    ...(dataHome === undefined ? [] : [`export ACC_DATA_HOME=${quote(dataHome)}`]),
    'if [ -x "$ACC_NODE" ] && [ -f "$ACC_RUNNER" ]; then',
    `  exec "$ACC_NODE" "$ACC_RUNNER" ${adapterId} "$@"`,
    "fi",
    "# Whatever node is current, if this package is installed under it: `acc-hook`",
    "# is the binary npm links, so a reinstall is found without knowing where.",
    "# It needs node too - its shebang is `env node` - and `exec` that fails ends",
    "# this script where it stands, taking the fallbacks below with it: measured",
    "# as exit 127 and `env: node: No such file or directory`, in place of the",
    "# line that says what to do.",
    "if command -v acc-hook >/dev/null 2>&1 && command -v node >/dev/null 2>&1; then",
    `  exec acc-hook ${adapterId} "$@"`,
    "fi",
    'if [ -f "$ACC_RUNNER" ] && command -v node >/dev/null 2>&1; then',
    `  exec node "$ACC_RUNNER" ${adapterId} "$@"`,
    "fi",
    "# Say so, and let the turn continue. Hooks fail open by design, and a broken",
    "# install must not be the reason somebody's session stops working.",
    'echo "acc: the hook runner installed here is gone (node: $ACC_NODE)." >&2',
    'echo "acc: run \'acc install\' to wire this client to the acc you have now." >&2',
    "exit 0",
    "",
  ].join("\n"));
  await chmod(target, 0o755);
  return target;
}

/**
 * Write the shim the skill's examples name.
 *
 * The skill used to carry the whole invocation in every example - a data home,
 * an interpreter and a script, around 200 bytes repeated 23 times - because the
 * command has to run where `acc` is not on PATH. One absolute path to a
 * generated script says the same thing in a third of the space and keeps the
 * guarantee that made the invocation absolute: nothing here is found on PATH.
 *
 * A data home belongs to the adapter, not to the machine. One client pins it
 * because its sandbox scrubs the environment; another deliberately leaves it
 * unset so an operator's own `ACC_DATA_HOME` still wins. A single shared shim
 * could not honour both, so each adapter writes its own beside its hook shim.
 *
 * Unlike the hook shim this fails loudly. A hook that cannot run must not stop
 * somebody's session, but this runs because an agent asked to coordinate, and
 * an agent told nothing went wrong improvises records by hand.
 */
export async function writeCliShim({ dir, cli = defaultCli(), node = process.execPath,
  name = "acc-cli.sh", dataHome }) {
  const target = path.join(dir, name);
  await mkdir(dir, { recursive: true });
  await writeFile(target, [
    "#!/bin/sh",
    "# Generated by ACC at install time. The paths are pinned for the reason the",
    "# hook shim pins them: a node version manager moves both the interpreter and",
    "# the directory global packages live in, so the pinned pair is tried first",
    "# and then asked for.",
    `ACC_NODE=${quote(node)}`,
    `ACC_CLI=${quote(cli)}`,
    ...(dataHome === undefined ? [] : [`export ACC_DATA_HOME=${quote(dataHome)}`]),
    'if [ -x "$ACC_NODE" ] && [ -f "$ACC_CLI" ]; then',
    '  exec "$ACC_NODE" "$ACC_CLI" "$@"',
    "fi",
    'if [ -f "$ACC_CLI" ] && command -v node >/dev/null 2>&1; then',
    '  exec node "$ACC_CLI" "$@"',
    "fi",
    'if command -v acc >/dev/null 2>&1; then',
    '  exec acc "$@"',
    "fi",
    'echo "acc: the CLI installed here is gone (node: $ACC_NODE)." >&2',
    'echo "acc: run \'acc install\' to wire this client to the acc you have now." >&2',
    "exit 1",
    "",
  ].join("\n"));
  await chmod(target, 0o755);
  return target;
}

/**
 * Remove a directory this adapter installed, unless it has been kept back.
 *
 * The installer decides what may be deleted by comparing what is on disk
 * against what ACC recorded writing. An adapter that removed its layout
 * unconditionally would undo that decision - and the case it undoes is exactly
 * the one that matters: someone put their own work inside a directory ACC
 * created, and a recognised path is not a reason to delete it.
 */
export async function removeInstalledTree(target, keep = []) {
  if (keep.includes(target)) return false;
  try {
    await lstat(target);
  } catch (error) {
    if (error.code === "ENOENT") return false;
    throw error;
  }
  await rm(target, { recursive: true, force: true });
  return true;
}

/** Where the CLI lives, resolved from this package rather than from PATH. */
export const defaultCli = () => ownBinary("acc.mjs");

/**
 * Bake the runnable command into the skill this adapter installs.
 *
 * What gets baked is the absolute path of the shim `writeCliShim` wrote, quoted
 * here so one place owns that. The shim's own contents decide how this client
 * reaches the CLI and whether it pins a data home.
 *
 * The skill is what tells an agent how to coordinate, and it used to say `acc`.
 * A hook never depends on PATH - its command is pinned at install time - but the
 * skill did, and on a machine where the package is not installed globally the
 * word `acc` runs nothing.
 *
 * A model that cannot run the command does not stop. Observed on a real Claude
 * Code session: told to take a task and finding no `acc`, it read the store's
 * JSON, worked out the schema, and wrote records and events by hand - inventing
 * an event type, a harness name, and its own generation tokens. So the command
 * is pinned here for the same reason it is pinned in the shim.
 */
export async function bakeSkillCommand({ root, cliShim }) {
  if (typeof cliShim !== "string" || cliShim === "") {
    throw new AccError(EXIT.DATA, "refusing to bake an empty skill command", { cliShim });
  }
  // A managed data home is "Application Support"; an unquoted path splits.
  const command = quote(cliShim);
  const baked = [];
  const walk = async directory => {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const full = path.join(directory, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.name === "SKILL.md") {
        const text = await readFile(full, "utf8");
        if (!text.includes(PLACEHOLDER)) continue;
        await writeFile(full, text.replaceAll(PLACEHOLDER, command));
        baked.push(full);
      }
    }
  };
  await walk(root);
  return baked;
}
